apiVersion: v1
kind: Service
metadata:
  name: gemma-vllm
  labels:
    app: gemma-vllm
spec:
  type: ClusterIP
  selector:
    app: gemma-vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
