apiVersion: inference.networking.gke.io/v1
kind: InferencePool
metadata:
  name: gemma-pool
spec:
  targetPortNumber: 8000
  selector:
    app: gemma-vllm
  extensionRef:
    name: gke-managed-endpoint-picker
